[env:airbrain_h743]
platform = ststm32
board = devebox_h743vitx
framework = arduino

lib_deps =
    adafruit/Adafruit NeoPixel
    stm32duino/STM32duino FreeRTOS

upload_protocol = dfu

build_flags =
    -DHAL_PCD_MODULE_ENABLED
    -DUSBCON
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -DUSBD_VID=0x0483
    -DUSBD_PID=0x5740
    -DHSE_VALUE=8000000U           ; Tell the core your crystal is 8MHz
    -DUSE_USB_HS_PH_IN_FS          ; Force USB to use internal HS-to-FS PHY
    -DUSBD_USE_CDC

board_build.usb_type = CDC
